export const DREAM_LIMITS = Object.freeze({
  worldRadius: 64,
  worldHeight: 64,
  blockTypes: 16,
  terrainOperations: 8,
  structures: 16,
  entityDefinitions: 6,
  entityInstances: 12,
  meshPartsPerHero: 32,
  physicsFields: 12,
  dialogueNodes: 24,
  storyBeats: 7,
  particles: 500,
  zones: 16,
  terrainLayers: 8,
  dialogueChoicesPerNode: 4,
  effectsPerBeat: 24,
  conditionDepth: 3,
  semanticAnchors: 8,
  textLength: 512,
  shortTextLength: 128,
  idLength: 64,
  pathPoints: 16,
  structureStates: 8,
  entityFeatures: 32,
  entityMaterials: 8,
  recognitionFeatures: 12,
  physicsTransitions: 12,
  physicsMaterials: 20,
  atmospherePatches: 8,
  audioCues: 16,
  variables: 12,
  verbs: 16,
  endings: 2,
  structureDimension: 64,
  entityScale: 4,
  entityFeatureSize: 8,
  fieldDimension: 128,
  structureCount: 32,
});

export const STRUCTURAL_LIMITS = Object.freeze({
  array: 128,
  textLength: 2_048,
  conditionChildren: 16,
});
